require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/**/*

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Rails/RequestReferer:
  EnforcedStyle: referrer

RSpec/ExampleLength:
  Max: 10

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

RSpec/NestedGroups:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/views/**/*.json.jbuilder'

Style/StringLiterals:
  EnforcedStyle: double_quotes
